rollout unnamedRollout "Untitled" width:338 height:204
(
	label warning "WARNING: Perspective view is currently enabled." pos:[49,6] width:239 height:19
	button saveAndContinue "Continue" pos:[253,159] width:78 height:34
	button saveCamerasAndContinue "Save Changes and Continue" pos:[94,158] width:150 height:34
	button exitButton "Exit" pos:[8,159] width:79 height:33
	dropDownList viewportSelection "Current Viewport Selection:" pos:[96,59] width:146 height:40
)